[workspace]
authors = ["Benjamin Badger <blbadger10@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "max"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
addition = "python3 addition.py"
test_addition = "pytest test_addition.py"
test = "python test.py"
module_test = "python module_test.py"
srm_test = "python srm.py"
embedding_test = "python embedding_test.py"

[dependencies]
modular = ">=26.2.0.dev2026021805,<27"
pytest = ">=9.0.2,<10"
pytorch = ">=2.10.0,<3"
