[workspace]
authors = ["blbadger <blbadger10@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "quickstart"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=26.2.0.dev2026022305,<27"
